export const formatName = (name: string) => {
    return encodeURIComponent(
        name
            .toLowerCase()
            .normalize("NFD")
            .replace(/[\u0300-\u036f]/g, "")
            .replaceAll(" ", "-")
            .replaceAll("/", "-")
            .replaceAll("?", "-")
            .replaceAll("&", "-")
            .replaceAll("=", "-")
            .replaceAll("%", "-")
            .replaceAll("#", "-")
            .replaceAll("$", "-")
            .replaceAll("@", "-")
            .replaceAll("`", "-")
            .replaceAll("\\", "-")
            .replaceAll(":", "-")
            .replaceAll(";", "-")
            .replaceAll("'", "-")
            .replaceAll('"', "-")
            .replaceAll(",", "-")
            .replaceAll(".", "-")
            .replaceAll("á", "a")
            .replaceAll("é", "e")
            .replaceAll("í", "i")
            .replaceAll("ó", "o")
            .replaceAll("ú", "u")
            .replaceAll("ñ", "n")
            .replaceAll("Á", "a")
            .replaceAll("É", "e")
            .replaceAll("Í", "i")
            .replaceAll("Ó", "o")
            .replaceAll("Ú", "u")
            .replaceAll("Ñ", "n")
    );
};